### PR TITLE
Reset default encoding in entrance to make it friendly to files which…

### PR DESCRIPTION
**Pull request by lanisle**
Reset default encoding in entrance to make it friendly to files which contain Chinese characters.

### CODE REVIEW

**Comment by hasegeli** [comment]
This looks like a bad practice [1] :(.  What encoding error do you get?

This script is also not the actual binary on the releases.  The actual one is generated by `setup.py`.  I added a note about it to the script.

Consider upgrading to Python 3 to avoid encoding problems.

[1] http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by lanisle** [comment]
> === CheckCommand "phpcs" on code/Third/Web/Template/Template.php at 0cb6c1a ===
ERROR: line 6: col 4: Content of the @author tag must be in the form "Display Name <username@example.com>"
WARNING: line 8: col 2: PHP version not specified
ERROR: line 8: col 2: Missing @category tag in class comment
ERROR: line 8: col 2: Missing @package tag in class comment
ERROR: line 8: col 2: Missing @license tag in class comment
ERROR: line 8: col 2: Missing @link tag in class comment
ERROR: line 24: col 8: Parameter comment must end with a full stop
ERROR: line 34: col 13: File is being conditionally included; use "include" instead
ERROR: line 38: col 18: VariTraceback (most recent call last):
  File "/root/githook/igcommit/igcommit/prereceive.py", line 97, in main
    state = Runner().run()
  File "/root/githook/igcommit/igcommit/prereceive.py", line 30, in run
    check.print_problems()
  File "/root/githook/igcommit/igcommit/base_check.py", line 72, in print_problems
    for severity, problem in self.get_problems():
  File "/root/githook/igcommit/igcommit/file_checks.py", line 257, in get_problems
    yield self._format_problem(line_buffer.pop(0).strip().decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 71: ordinal not in range(128)
able "left_delimiter" is not in valid camel caps format
ERROR: line 39: col 18: Variable "right_delimiter" is not in valid camel caps format
ERROR: line 44: col 9: Inline comments must end in full-stops, exclamation marks, or question marks
ERROR: line 44: col 9: There must be no blank line following an inline comment

I have mailed you with that file.

**Comment by hasegeli** [comment]
My `phpcs` refused to emit any unicode characters no matter what I do, but I managed to reproduce the problem by creating a syntax checker script like this:

```sh
#!/bin/sh
read
echo 模板类
```

The problem was not specifying encoding on `decode()` calls.  Now it is fixed.

**Comment by lanisle** [comment]
Thanks for your work. 💯

**Comment by lanisle** [comment]
> ...skipped...
remote: ERROR: line 463: col 13: Inline comments must end in full-stops, exclamation marks, or question marks
remote: ERROR: line 464: col 30: Variable "_php_resource_dir" is not in valid camel caps format
remote: ERROR: line 465: col 17: Inline comments must start with a capital letter
remote: ERROR: line 465: col 17: Inline comments must end in fullTraceback (most recent call last):
remote:   File "/root/githook/igcommit/igcommit/prereceive.py", line 97, in main
remote:     state = Runner().run()
remote:   File "/root/githook/igcommit/igcommit/prereceive.py", line 30, in run
remote:     check.print_problems()
remote:   File "/root/githook/igcommit/igcommit/base_check.py", line 76, in print_problems
remote:     print(severity.name + ': ' + problem)
remote: UnicodeEncodeError: 'ascii' codec can't encode characters in position 73-75: ordinal not in range(128)
remote: -stops, exclamation marks, or question marks
remote: ERROR: line 466: col 24: Variable "_php_resource_dir" is not in valid camel caps format
remote: ERROR: line 466: col 63: Variable "_php_resource_dir" is not in valid camel caps format
remote: ERROR: line 468: col 24: TRUE, FALSE and NULL must be uppercase; expected "TRUE" but found "true"
remote: ERROR: line 469: col 13: No blank line found after control structure
remote: ERROR: line 470: col 13: Inline comments must start with a capital letter
remote: ERROR: line 470: col 13: Inline comments must end in full-stops, exclamation marks, or question marks
remote: ERROR: line 471: col 54: TRUE, FALSE and NULL must be uppercase; expected "FALSE" but found "false"
remote: ERROR: line 473: col 13: No blank line found after control structure
remote: ERROR: line 474: col 13: Inline comments must start with a capital letter
remote: ERROR: line 474: col 13: Inline comments must end in full-stops, exclamation marks, or question marks
remote: ERROR: line 478: col 35: Variable "_filepath" is not in valid camel caps format
remote:
remote: === CheckCommand "phpcs" on code/Third/Web/Template/Template.php at c43687af ===
remote: ERROR: line 6: col 4: Content of the @author tag must be in the form "Display Name <username@example.com>"
remote: WARNING: line 8: col 2: PHP version not specified
remote: ERROR: line 8: col 2: Missing @category tag in class comment
remote: ERROR: line 8: col 2: Missing @package tag in class comment
remote: ERROR: line 8: col 2: Missing @license tag in class comment
remote: ERROR: line 8: col 2: Missing @link tag in class comment
remote: ERROR: line 24: col 8: Parameter comment must end with a full stop
remote: ERROR: line 34: col 13: File is being conditionally included; use "include" instead
remote: ERROR: line 38: col 18: Variable "left_delimiter" is not in valid camel caps format
remote: ERROR: line 39: col 18: Variable "right_delimiter" is not in valid camel caps format
remote: ERROR: line 44: col 9: Inline comments must end in full-stops, exclamation marks, or question marks
remote: ERROR: line 44: col 9: There must be no blank line following an inline comment
remote:
remote: === CheckCommand "phpcs" on code/allowDebugIP.cfg.php at c43687af ===
remote: ERROR: line 5: col 4: Content of the @author tag must be in the form "Display Name <username@example.com>"
remote: WARNING: line 7: col 2: PHP version not specified
remote: ERROR: line 7: col 2: Missing @category tag in class comment
remote: ERROR: line 7: col 2: Missing @package tag in class comment
remote: ERROR: line 7: col 2: Missing @license tag in class comment
remote: ERROR: line 7: col 2: Missing @link tag in class comment
To /root/githook/server.git/
 \*[new branch]      master -> master

There are two issues here:

1) Encoding issue
2) Even the hook found problems from contents, especially being with an encoding error. The commit are still be accepted by remote...

**Comment by lanisle** [comment]
I deleted code/Third/Web/Template/Smarty/sysplugins/smarty_security.php and tested again. The output is weird...

Please check weird_logs.zip for details.

**Comment by hasegeli** [comment]
> Even the hook found problems from contents, especially being with an encoding error. The commit are still be accepted by remote...

This is by design.  I don't want to block people when we get something wrong.

**Comment by hasegeli** [comment]
I have modified the script to exercise the code path on the traceback, but couldn't make it fail:

```sh
#!/bin/sh
read
echo error:模板类
```

I have Python 2.7.12 with py27-enum34-1.1.6 package.  What version are you using?  Have you tried using Python 3?

In the mean time, I made the literal strings unicode on Python 2 with `from __future__ import unicode_literals`.  Maybe this would fix your problem.

I have also tackled with the traceback appearing in between the problems by flushing stdout before printing it.  Let me know, if it helps.

**Comment by lanisle** [comment]
Hi, 

I have Python 2.7.13 with py27-enum34-1.1.6 package. 

The improvement you made is useful. But the encoding issues still exists.

See this:

> $ git add 5.php && git commit -m 's' && git push origin master
[master f96c32c] s
 1 file changed, 13 insertions(+)
 create mode 100644 5.php
Counting objects: 2, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 221 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: === CheckCommand "phpcs" on 5.php at f96c32cd ===
remote: ERROR: line 5: col 4: Content of the @author tag must be in the form "Display Name <username@example.com>"
remote: WARNING: line 7: col 2: PHP version not specified
remote: ERROR: line 7: col 2: Missing @category tag in class comment
remote: ERROR: line 7: col 2: Missing @package tag in class comment
remote: ERROR: line 7: col 2: Missing @license tag in class comment
remote: ERROR: line 7: col 2: Missing @link tag in class comment
remote: Traceback (most recent call last):
remote:   File "/opt/gitlab-extensions/pre-receive/igcommit/igcommit/prereceive.py", line 101, in main
remote:     state = Runner().run()
remote:   File "/opt/gitlab-extensions/pre-receive/igcommit/igcommit/prereceive.py", line 33, in run
remote:     check.print_problems()
remote:   File "/opt/gitlab-extensions/pre-receive/igcommit/igcommit/base_check.py", line 78, in print_problems
remote:     print('{}: {}'.format(severity.name, problem))
remote: UnicodeEncodeError: 'ascii' codec can't encode characters in position 73-75: ordinal not in range(128)
To git.skyunion.net:zhengwei/test.git
   e59f370..f96c32c  master -> master

The 5.php has been shared(Dropbox) with you now.

I am trying Python 3...

**Comment by lanisle** [comment]
It's all ok with Python 3.

**Comment by hasegeli** [comment]
I am still failing to reproduce this, but trying to fix blindly.  Unfortunately, Python 2 is still very common out in the wild.  People wouldn't give the tool a second chance, if we fail with encoding error on their first try.

I now added `coding: utf-8` to every file.  Could you please test again on Python 2?  If that wouldn't help either, we can try something like `b'{}: {}'.decode('utf-8').format(severity.name, problem)`.

**Comment by hasegeli** [comment]
Any luck testing this again on Python 2?

**Comment by hasegeli** [comment]
I assume my last change fixed your problem.

**Pull request closed without merging**
